export interface output_d{
    output: string
    color_class?: string
}
export interface output_line{
    message_type: output_d
    text: output_d
    perc: number
}

export const blueScreenLines: output_line[] = [
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "KERNEL_SECURITY_CHECK_FAILURE" }, perc: 0.051353 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "A critical system process has terminated unexpectedly" }, perc: 0.012322 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Stop code: 0x00000139" }, perc: 0.00524 },
    { message_type: { output: "INFO" }, text: { output: "Collecting diagnostic information..." }, perc: 0.002772 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "IRQL_NOT_LESS_OR_EQUAL" }, perc: 0.012521 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Attempted to access pageable memory at IRQL DISPATCH_LEVEL" }, perc: 0.014343 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Faulting module: ntoskrnl.exe" }, perc: 0.005335 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Exception code: 0xC0000005 (ACCESS_VIOLATION)" }, perc: 0.013606 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Faulting address: 0xFFFFF80412A93C10" }, perc: 0.003302 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "MEMORY_MANAGEMENT" }, perc: 0.011593 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Page fault in nonpaged area" }, perc: 0.009561 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Physical memory dump initiated" }, perc: 0.00568 },
    { message_type: { output: "INFO" }, text: { output: "Collecting error information: 0% complete" }, perc: 0.005088 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "DRIVER_IRQL_NOT_LESS_OR_EQUAL" }, perc: 0.048007 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Faulting driver: nvlddmkm.sys" }, perc: 0.005829 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Driver version mismatch detected" }, perc: 0.013718 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Driver signature could not be verified" }, perc: 0.004811 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "SYSTEM_THREAD_EXCEPTION_NOT_HANDLED" }, perc: 0.009105 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Thread ID: 0x0000000000001A4C" }, perc: 0.005528 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Unhandled kernel exception in thread" }, perc: 0.012761 },
    { message_type: { output: "INFO" }, text: { output: "Collecting error information: 12% complete" }, perc: 0.00563 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "CRITICAL_PROCESS_DIED" }, perc: 0.008534 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Process csrss.exe terminated unexpectedly" }, perc: 0.009854 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "System stability compromised" }, perc: 0.004435 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "PAGE_FAULT_IN_NONPAGED_AREA" }, perc: 0.011243 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Faulting module: storahci.sys" }, perc: 0.007588 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Attempted to read from invalid memory address" }, perc: 0.009993 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "NTFS_FILE_SYSTEM" }, perc: 0.008591 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Volume C: reports corruption at sector 0x4F2A1" }, perc: 0.007776 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "File system structure error detected" }, perc: 0.01372 },
    { message_type: { output: "INFO" }, text: { output: "Collecting error information: 27% complete" }, perc: 0.005982 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "DPC_WATCHDOG_VIOLATION" }, perc: 0.008546 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "A single DPC or ISR exceeded its time allotment" }, perc: 0.004468 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Watchdog timeout after 5000ms" }, perc: 0.009407 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "UNEXPECTED_KERNEL_MODE_TRAP" }, perc: 0.014005 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Trap number: 0x00000008 (double fault)" }, perc: 0.003762 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Kernel stack overflow detected" }, perc: 0.0091 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "VIDEO_TDR_FAILURE" }, perc: 0.00968 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Faulting module: nvlddmkm.sys" }, perc: 0.00722 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "GPU driver failed to respond within timeout" }, perc: 0.009539 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Attempting driver reset..." }, perc: 0.008219 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Driver reset failed, GPU unresponsive" }, perc: 0.010225 },
    { message_type: { output: "INFO" }, text: { output: "Collecting error information: 41% complete" }, perc: 0.005306 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "BAD_POOL_HEADER" }, perc: 0.049916 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Pool header corruption detected at 0xFFFFC0001A9B2000" }, perc: 0.004631 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Kernel memory pool integrity check failed" }, perc: 0.013696 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "KMODE_EXCEPTION_NOT_HANDLED" }, perc: 0.014519 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Exception code: 0x80000003 (breakpoint)" }, perc: 0.004373 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Debugger not attached, cannot recover" }, perc: 0.010482 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Attempting automatic recovery..." }, perc: 0.003412 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Automatic recovery failed" }, perc: 0.009518 },
    { message_type: { output: "INFO" }, text: { output: "Collecting error information: 56% complete" }, perc: 0.003814 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "INACCESSIBLE_BOOT_DEVICE" }, perc: 0.011552 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Boot volume signature mismatch" }, perc: 0.006088 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Boot device driver failed to initialize" }, perc: 0.010482 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "INTERRUPT_EXCEPTION_NOT_HANDLED" }, perc: 0.00929 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Interrupt vector: 0x0D (general protection fault)" }, perc: 0.005999 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "CPU exception raised in interrupt context" }, perc: 0.010479 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "REGISTRY_ERROR" }, perc: 0.010455 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Registry hive SYSTEM reports inconsistency" }, perc: 0.008166 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Failed to load registry hive" }, perc: 0.011964 },
    { message_type: { output: "INFO" }, text: { output: "Collecting error information: 68% complete" }, perc: 0.001746 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "FATAL_UNHANDLED_HARD_ERROR" }, perc: 0.014267 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Component: wininit.exe" }, perc: 0.008148 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Hard error status: 0xC000021A" }, perc: 0.053408 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "CACHE_MANAGER" }, perc: 0.014408 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Cache coherency check failed" }, perc: 0.00366 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Memory cache corruption detected" }, perc: 0.014028 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "SPIN_LOCK_ALREADY_OWNED" }, perc: 0.009357 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Deadlock detected on kernel spinlock" }, perc: 0.0076 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Lock owner thread unresponsive" }, perc: 0.012525 },
    { message_type: { output: "INFO" }, text: { output: "Collecting error information: 79% complete" }, perc: 0.007034 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "MULTIPROCESSOR_CONFIGURATION_NOT_SUPPORTED" }, perc: 0.010188 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "CPU topology mismatch detected" }, perc: 0.006509 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "PROCESS1_INITIALIZATION_FAILED" }, perc: 0.014164 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "smss.exe failed to initialize subsystem" }, perc: 0.003783 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "SESSION3_INITIALIZATION_FAILED" }, perc: 0.009458 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "HAL_INITIALIZATION_FAILED" }, perc: 0.011775 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Hardware abstraction layer mismatch" }, perc: 0.003809 },
    { message_type: { output: "INFO" }, text: { output: "Collecting error information: 88% complete" }, perc: 0.001967 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "CLOCK_WATCHDOG_TIMEOUT" }, perc: 0.008402 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Processor 2 failed to respond to clock interrupt" }, perc: 0.004916 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "System clock synchronization lost" }, perc: 0.012354 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "DRIVER_POWER_STATE_FAILURE" }, perc: 0.011207 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Faulting driver: usbhub.sys" }, perc: 0.006251 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Device failed to enter requested power state" }, perc: 0.00847 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Preparing crash dump for analysis..." }, perc: 0.00364 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Writing physical memory dump: 32768MB" }, perc: 0.011828 },
    { message_type: { output: "INFO" }, text: { output: "Collecting error information: 95% complete" }, perc: 0.00254 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Dump file location: C:\Windows\MEMORY.DMP" }, perc: 0.003181 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Crash dump write incomplete, disk error encountered" }, perc: 0.008689 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Attempting to send error report to support..." }, perc: 0.006498 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Error report transmission failed: no network" }, perc: 0.014285 },
    { message_type: { output: "INFO" }, text: { output: "Collecting error information: 100% complete" }, perc: 0.004443 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "If this is the first time you've seen this error, restart your system" }, perc: 0.003147 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "If problems continue, disable or remove any newly installed hardware or software" }, perc: 0.004126 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "STOP: 0x0000007E (0xFFFFFFFFC0000005, 0xFFFFF80412A93C10, 0xFFFFF88003A9D5A8, 0xFFFFF88003A9CE00)" }, perc: 0.012549 },
    { message_type: { output: "INFO" }, text: { output: "Preparing to restart..." }, perc: 0.006105 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Restart in progress, do not power off device" }, perc: 0.004184 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "System halted" }, perc: 0.011217 },
]