
export interface output_d{
    output: string
    color_class?: string
}
export interface output_line{
    opening_br: output_d
    message_type: output_d
    closing_br: output_d
    text: output_d
    perc: number
}

export const bootingUpLines: output_line[] = [
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Initializing kernel v5.14.2..." }, perc: 0.009523 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Kernel initialized" }, perc: 0.000626 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: `Detecting CPU cores: ${navigator.hardwareConcurrency} found` }, perc: 0.003883 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "CPU frequency scaling enabled" }, perc: 0.000424 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Detecting CPU vendor..." }, perc: 0.001301 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "CPU vendor: GenuineIntel" }, perc: 0.0025 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Reading ACPI tables..." }, perc: 0.003776 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "ACPI tables parsed: 14 entries" }, perc: 0.000621 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Initializing memory controller..." }, perc: 0.015937 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Memory controller online" }, perc: 0.001328 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Running memory self-test..." }, perc: 0.001803 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Memory test passed: 32768MB OK" }, perc: 0.000793 },
    { opening_br: { output: "[" }, message_type: { output: "WARNING", color_class: "warning" }, closing_br: { output: "]" }, text: { output: "Memory module in slot B2 running below rated speed" }, perc: 0.002575 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "ECC protection enabled" }, perc: 0.001374 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Initializing interrupt controller..." }, perc: 0.005066 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "APIC initialized, 24 IRQ lines mapped" }, perc: 0.001112 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Calibrating TSC..." }, perc: 0.003651 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "TSC calibrated: 3200.14 MHz" }, perc: 0.001149 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Mounting root filesystem (/dev/sda1)..." }, perc: 0.001365 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Root filesystem mounted read-write" }, perc: 0.000723 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking filesystem journal..." }, perc: 0.002111 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Journal recovery not required" }, perc: 0.000706 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Loading kernel modules..." }, perc: 0.002638 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Module ext4.ko loaded" }, perc: 0.000605 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Module nvidia.ko loaded" }, perc: 0.00168 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Module usbcore.ko loaded" }, perc: 0.001196 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Module xhci_hcd.ko loaded" }, perc: 0.001373 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Module snd_hda_intel.ko loaded" }, perc: 0.000856 },
    { opening_br: { output: "[" }, message_type: { output: "WARNING", color_class: "warning" }, closing_br: { output: "]" }, text: { output: "Module btrfs.ko built against different kernel ABI" }, perc: 0.004582 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting udev device manager..." }, perc: 0.003915 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "udev daemon started (pid 214)" }, perc: 0.001443 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Enumerating input devices..." }, perc: 0.001311 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Input device registered: AT Translated Set 2 keyboard" }, perc: 0.000691 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Input device registered: PS/2 Mouse" }, perc: 0.001689 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Scanning PCI bus..." }, perc: 0.002438 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Found 12 devices on PCI bus" }, perc: 0.002761 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "PCI device 00:02.0 (VGA controller) initialized" }, perc: 0.000974 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "PCI device 00:1f.3 (Audio controller) initialized" }, perc: 0.00066 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Scanning USB buses..." }, perc: 0.002231 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "USB controller xHCI initialized" }, perc: 0.001623 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "USB device connected: hub (4 ports)" }, perc: 0.00062 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: `Clock synced: ${new Date().toISOString()}` }, perc: 0.001049 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting system logger..." }, perc: 0.00137 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "syslogd started (pid 341)" }, perc: 0.001223 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting kernel log daemon..." }, perc: 0.002867 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "klogd started (pid 342)" }, perc: 0.00086 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking disk integrity..." }, perc: 0.003294 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Disk check passed, 0 bad sectors" }, perc: 0.005396 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Reading SMART attributes..." }, perc: 0.003903 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "SMART status: PASSED" }, perc: 0.00069 },
    { opening_br: { output: "[" }, message_type: { output: "WARNING", color_class: "warning" }, closing_br: { output: "]" }, text: { output: "Disk /dev/sda reallocated sector count nonzero" }, perc: 0.002629 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Mounting swap partition..." }, perc: 0.002993 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Swap enabled (4096MB)" }, perc: 0.00159 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Initializing cgroups..." }, perc: 0.00318 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "cgroup v2 hierarchy mounted" }, perc: 0.001645 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting init system..." }, perc: 0.002374 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "init system PID 1 ready" }, perc: 0.001196 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Loading system services..." }, perc: 0.004226 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Service networkd.service started" }, perc: 0.001446 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Service dbus.service started" }, perc: 0.000296 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Service polkit.service started" }, perc: 0.000324 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Service udisks2.service started" }, perc: 0.001594 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Service cron.service started" }, perc: 0.002818 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Service rsyslog.service started" }, perc: 0.001695 },
    { opening_br: { output: "[" }, message_type: { output: "WARNING", color_class: "warning" }, closing_br: { output: "]" }, text: { output: "Service bluetooth.service failed to start cleanly, retrying" }, perc: 0.004013 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Service bluetooth.service started" }, perc: 0.00142 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting firewall..." }, perc: 0.001695 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Firewall rules loaded: 42 rules active" }, perc: 0.001108 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting SSH daemon..." }, perc: 0.004664 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "sshd listening on port 22" }, perc: 0.000609 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Mounting external volumes..." }, perc: 0.004095 },
    { opening_br: { output: "[" }, message_type: { output: "ERROR", color_class: "error" }, closing_br: { output: "]" }, text: { output: "Failed to mount /dev/sdb1: device not found" }, perc: 0.054084 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Continuing without external volume" }, perc: 0.003776 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Mounting network shares..." }, perc: 0.003248 },
    { opening_br: { output: "[" }, message_type: { output: "WARNING", color_class: "warning" }, closing_br: { output: "]" }, text: { output: "NFS share 10.0.0.5:/export unreachable, will retry in background" }, perc: 0.003047 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking for filesystem quota..." }, perc: 0.00353 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Quota subsystem enabled" }, perc: 0.000621 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting audio subsystem..." }, perc: 0.003701 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "ALSA sound card detected: HDA Intel PCH" }, perc: 0.001634 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting PulseAudio server..." }, perc: 0.001465 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "PulseAudio daemon started" }, perc: 0.001284 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting display manager..." }, perc: 0.00171 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Display manager ready on :0" }, perc: 0.00114 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Loading X11 drivers..." }, perc: 0.004314 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "X11 driver loaded: nvidia" }, perc: 0.000577 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Detecting connected monitors..." }, perc: 0.002903 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Monitor detected: DP-1 2560x1440@144Hz" }, perc: 0.000986 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Verifying user credentials cache..." }, perc: 0.00387 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Credentials cache valid" }, perc: 0.000441 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Loading user profile..." }, perc: 0.002537 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "User profile loaded: admin" }, perc: 0.000663 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Mounting home directory..." }, perc: 0.002973 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Home directory mounted (/home/admin)" }, perc: 0.000707 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting session manager..." }, perc: 0.004867 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Session manager started (pid 981)" }, perc: 0.001569 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Initializing font cache..." }, perc: 0.001384 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Font cache rebuilt: 412 fonts indexed" }, perc: 0.001531 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting notification daemon..." }, perc: 0.004879 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Notification daemon ready" }, perc: 0.000541 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking for system updates..." }, perc: 0.002035 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "System up to date" }, perc: 0.000382 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Verifying package database integrity..." }, perc: 0.005115 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Package database OK: 2481 packages" }, perc: 0.001455 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting cron scheduler..." }, perc: 0.002871 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Cron scheduler active, 6 jobs queued" }, perc: 0.001767 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Initializing thermal management..." }, perc: 0.004049 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Thermal zones monitored: 4" }, perc: 0.000734 },
    { opening_br: { output: "[" }, message_type: { output: "WARNING", color_class: "warning" }, closing_br: { output: "]" }, text: { output: "CPU core 3 temperature approaching threshold (78C)" }, perc: 0.053266 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Adjusting fan curve..." }, perc: 0.013204 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Fan speed increased to 62%" }, perc: 0.001039 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting power management daemon..." }, perc: 0.001811 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Power profile set to balanced" }, perc: 0.000414 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking battery status..." }, perc: 0.003557 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Battery: 87% charged, AC connected" }, perc: 0.000643 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Initializing virtual filesystem cache..." }, perc: 0.004735 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "VFS cache warmed: 18432 inodes" }, perc: 0.001174 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting container runtime..." }, perc: 0.002856 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Container runtime ready (containerd 1.7.11)" }, perc: 0.001068 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Loading firewall zone definitions..." }, perc: 0.001998 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Firewall zones loaded: public, trusted" }, perc: 0.000648 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting time synchronization service..." }, perc: 0.003863 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "timesyncd active, drift 0.002s" }, perc: 0.000763 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Verifying boot partition signature..." }, perc: 0.001472 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Boot partition signature valid" }, perc: 0.001771 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Loading TPM state..." }, perc: 0.001475 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "TPM 2.0 module initialized" }, perc: 0.000688 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Unsealing disk encryption keys..." }, perc: 0.004698 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Disk encryption keys unsealed" }, perc: 0.000842 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Mounting encrypted volume..." }, perc: 0.00451 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Encrypted volume mounted (/dev/mapper/crypt0)" }, perc: 0.0012 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting log rotation service..." }, perc: 0.013782 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "logrotate configured: daily rotation" }, perc: 0.000738 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Finalizing boot sequence..." }, perc: 0.00493 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "All systems operational" }, perc: 0.000466 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: `Boot complete in ${(performance.now() / 1000).toFixed(3)}s` }, perc: 0.00339 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting network time protocol daemon..." }, perc: 0.003596 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "chronyd started, tracking 4 NTP sources" }, perc: 0.000597 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Verifying hardware clock..." }, perc: 0.002236 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "RTC battery voltage nominal" }, perc: 0.001634 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting IPv6 stack..." }, perc: 0.001551 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "IPv6 link-local address assigned" }, perc: 0.002496 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking for rogue DHCP servers..." }, perc: 0.003725 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "No rogue DHCP servers detected" }, perc: 0.001391 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting firewall connection tracking..." }, perc: 0.006213 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Connection tracking table initialized: 65536 entries" }, perc: 0.001601 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Process accounting enabled" }, perc: 0.001102 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Loading locale definitions..." }, perc: 0.003507 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Locale set: en_US.UTF-8" }, perc: 0.000484 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting timezone service..." }, perc: 0.00477 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Timezone set: America/New_York" }, perc: 0.001568 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking system hostname..." }, perc: 0.002021 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Hostname resolved: workstation-07" }, perc: 0.000448 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting hostname service..." }, perc: 0.004711 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Hostname service active" }, perc: 0.001213 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Verifying network route table..." }, perc: 0.004893 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Route table valid: 3 routes" }, perc: 0.001739 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting reverse path filter..." }, perc: 0.016324 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Reverse path filtering enabled" }, perc: 0.000787 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking MTU settings..." }, perc: 0.004384 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "MTU set to 1500 on all interfaces" }, perc: 0.001494 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting connection quality monitor..." }, perc: 0.004325 },
    { opening_br: { output: "[" }, message_type: { output: "WARNING", color_class: "warning" }, closing_br: { output: "]" }, text: { output: "Packet loss detected on eth0: 0.4%" }, perc: 0.045714 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting bandwidth throttling service..." }, perc: 0.00207 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Bandwidth policies loaded" }, perc: 0.000976 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Verifying storage encryption keys..." }, perc: 0.004357 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Encryption key rotation up to date" }, perc: 0.000331 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting backup verification job..." }, perc: 0.002492 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Last backup integrity: verified" }, perc: 0.001725 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking for filesystem snapshots..." }, perc: 0.003742 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "3 snapshots available for rollback" }, perc: 0.001746 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting session recording daemon..." }, perc: 0.004931 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Session recording disabled by policy" }, perc: 0.00173 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Loading accessibility services..." }, perc: 0.005024 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Accessibility services ready" }, perc: 0.000456 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting screen reader support..." }, perc: 0.00409 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Screen reader support loaded" }, perc: 0.001192 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking display color depth..." }, perc: 0.00272 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Color depth: 32-bit" }, perc: 0.000672 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting desktop search indexer..." }, perc: 0.001189 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Search index up to date: 48213 items" }, perc: 0.001091 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Verifying application sandboxing..." }, perc: 0.004143 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Sandbox profiles active" }, perc: 0.000834 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting crash reporter service..." }, perc: 0.003833 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Crash reporter armed" }, perc: 0.00076 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking for kernel panics in previous session..." }, perc: 0.004055 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "No kernel panics recorded" }, perc: 0.000753 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting final system validation..." }, perc: 0.002788 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "System validation passed" }, perc: 0.000484 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Probing SATA controller ports..." }, perc: 0.004935 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "SATA port 0: device detected (SSD)" }, perc: 0.00163 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "SATA port 1: device detected (HDD)" }, perc: 0.00074 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Reading partition tables..." }, perc: 0.001184 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Partition table read: GPT, 6 partitions" }, perc: 0.000931 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Verifying bootloader configuration..." }, perc: 0.003795 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Bootloader config valid (GRUB 2.06)" }, perc: 0.000949 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Loading initramfs..." }, perc: 0.003071 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "initramfs unpacked: 38MB" }, perc: 0.001472 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Switching root..." }, perc: 0.001521 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Root switch complete" }, perc: 0.001231 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting device mapper..." }, perc: 0.004449 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Device mapper initialized" }, perc: 0.00129 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Scanning for LVM volume groups..." }, perc: 0.004922 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Volume group 'vg0' activated" }, perc: 0.000998 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Logical volume 'lv-root' active" }, perc: 0.000403 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Logical volume 'lv-swap' active" }, perc: 0.001226 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Initializing random number generator..." }, perc: 0.003961 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Entropy pool seeded (256 bits)" }, perc: 0.000656 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Loading /etc/fstab entries..." }, perc: 0.001205 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "fstab parsed: 5 mount points" }, perc: 0.001434 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking for stale lock files..." }, perc: 0.002879 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "No stale locks found" }, perc: 0.001712 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting hardware watchdog..." }, perc: 0.001383 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Watchdog armed, timeout 30s" }, perc: 0.00155 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Initializing PCIe link training..." }, perc: 0.004381 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "PCIe link trained: Gen4 x16" }, perc: 0.001756 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Enumerating storage controllers..." }, perc: 0.004974 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "NVMe controller detected: Samsung 980 PRO" }, perc: 0.001201 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Reading NVMe namespace info..." }, perc: 0.003197 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Namespace 1: 1024GB, 512B sectors" }, perc: 0.001105 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Verifying firmware checksums..." }, perc: 0.00415 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Firmware checksum verified" }, perc: 0.000679 },
    { opening_br: { output: "[" }, message_type: { output: "WARNING", color_class: "warning" }, closing_br: { output: "]" }, text: { output: "Secondary firmware bank checksum mismatch, using primary" }, perc: 0.004573 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Initializing keyboard controller..." }, perc: 0.003263 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Keyboard controller ready" }, perc: 0.000701 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Setting console keymap..." }, perc: 0.002323 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Keymap set to us-qwerty" }, perc: 0.000768 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Loading console font..." }, perc: 0.001735 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Console font loaded: Lat2-Terminus16" }, perc: 0.001321 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting virtual terminal manager..." }, perc: 0.001439 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "6 virtual terminals allocated" }, perc: 0.001098 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Initializing PAM authentication stack..." }, perc: 0.002008 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "PAM modules loaded: 8" }, perc: 0.001633 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking password policy..." }, perc: 0.003958 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Password policy loaded" }, perc: 0.001427 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting D-Bus system bus..." }, perc: 0.001206 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "D-Bus system bus online" }, perc: 0.001409 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Registering system services with D-Bus..." }, perc: 0.004987 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "32 services registered" }, perc: 0.001401 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting hardware abstraction layer..." }, perc: 0.00359 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "HAL daemon started" }, perc: 0.00062 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Probing thermal sensors..." }, perc: 0.001298 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Thermal sensor array online: 6 sensors" }, perc: 0.001299 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Calibrating fan RPM curve..." }, perc: 0.001841 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Fan curve calibrated" }, perc: 0.000484 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting UPS monitoring daemon..." }, perc: 0.00129 },
    { opening_br: { output: "[" }, message_type: { output: "WARNING", color_class: "warning" }, closing_br: { output: "]" }, text: { output: "UPS not detected, skipping power-loss protection" }, perc: 0.014136 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Initializing RAID controller..." }, perc: 0.001724 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "RAID array 'md0' assembled (RAID 1, 2 disks)" }, perc: 0.00037 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking RAID array health..." }, perc: 0.002027 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "RAID array health: optimal" }, perc: 0.001421 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Mounting /var partition..." }, perc: 0.004184 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "/var mounted successfully" }, perc: 0.000668 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Mounting /tmp as tmpfs..." }, perc: 0.00126 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "/tmp mounted (tmpfs, 2048MB)" }, perc: 0.001774 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Cleaning temporary files..." }, perc: 0.003777 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Temporary files purged: 184 files removed" }, perc: 0.001259 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting mail transfer agent..." }, perc: 0.004972 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Postfix MTA started" }, perc: 0.000326 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting print spooler..." }, perc: 0.001686 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "CUPS daemon started, 1 printer detected" }, perc: 0.001129 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Loading printer drivers..." }, perc: 0.003974 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Driver loaded: HP LaserJet Pro" }, perc: 0.000544 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting Bluetooth stack..." }, perc: 0.004167 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Bluetooth adapter initialized (BT 5.2)" }, perc: 0.001507 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Scanning for paired devices..." }, perc: 0.004235 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "2 paired devices found" }, perc: 0.001297 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting fingerprint reader service..." }, perc: 0.002765 },
    { opening_br: { output: "[" }, message_type: { output: "ERROR", color_class: "error" }, closing_br: { output: "]" }, text: { output: "Fingerprint reader not found on USB bus" }, perc: 0.046659 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Biometric login disabled for this session" }, perc: 0.003686 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting webcam service..." }, perc: 0.004265 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Webcam initialized: 1080p @ 30fps" }, perc: 0.001183 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Initializing microphone array..." }, perc: 0.005109 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Microphone array calibrated" }, perc: 0.000809 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Loading GPU compute drivers..." }, perc: 0.002661 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "CUDA runtime initialized: v12.4" }, perc: 0.0008 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Verifying GPU memory integrity..." }, perc: 0.004464 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "GPU memory ECC check passed" }, perc: 0.001716 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting compositor..." }, perc: 0.00449 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Compositor started (vsync enabled)" }, perc: 0.000939 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Loading window manager..." }, perc: 0.005035 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Window manager initialized" }, perc: 0.00149 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Restoring previous session state..." }, perc: 0.003112 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Session state restored: 4 windows" }, perc: 0.001376 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting clipboard manager..." }, perc: 0.004581 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Clipboard manager ready" }, perc: 0.000424 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting application indexer..." }, perc: 0.002156 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Indexed 312 installed applications" }, perc: 0.001198 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking for orphaned processes..." }, perc: 0.001297 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "No orphaned processes found" }, perc: 0.000564 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting resource monitor..." }, perc: 0.004366 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Resource monitor active" }, perc: 0.001597 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Sampling initial system load..." }, perc: 0.008903 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Load average: 0.12, 0.08, 0.05" }, perc: 0.000422 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting VPN client service..." }, perc: 0.003132 },
    { opening_br: { output: "[" }, message_type: { output: "WARNING", color_class: "warning" }, closing_br: { output: "]" }, text: { output: "VPN configuration file missing, service idle" }, perc: 0.004769 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting DNS caching resolver..." }, perc: 0.003141 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Local DNS cache ready (dnsmasq)" }, perc: 0.000433 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Verifying certificate store..." }, perc: 0.003943 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Certificate store verified: 187 trusted CAs" }, perc: 0.001155 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking system entropy levels..." }, perc: 0.003301 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Entropy level sufficient: 3847 bits available" }, perc: 0.001398 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting audit daemon..." }, perc: 0.003987 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "auditd started, logging enabled" }, perc: 0.000667 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Loading SELinux policy..." }, perc: 0.001951 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "SELinux policy loaded: enforcing mode" }, perc: 0.001088 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting AppArmor profiles..." }, perc: 0.001921 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "AppArmor profiles loaded: 24 active" }, perc: 0.001011 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Verifying kernel module signatures..." }, perc: 0.00508 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "All module signatures valid" }, perc: 0.000714 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting system health check..." }, perc: 0.001957 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Health check passed: all subsystems nominal" }, perc: 0.001721 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Registering with service discovery..." }, perc: 0.002277 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Registered as node 'workstation-07'" }, perc: 0.001114 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting telemetry collector..." }, perc: 0.001686 },
    { opening_br: { output: "[" }, message_type: { output: "WARNING", color_class: "warning" }, closing_br: { output: "]" }, text: { output: "Telemetry endpoint unreachable, buffering locally" }, perc: 0.004031 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting backup scheduler..." }, perc: 0.003473 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Backup scheduler active, next run in 6h" }, perc: 0.000947 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking disk space thresholds..." }, perc: 0.001387 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Disk usage: 42% (218GB free)" }, perc: 0.001002 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting package manager cache updater..." }, perc: 0.002782 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Package cache refreshed" }, perc: 0.002818 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Verifying system integrity (checksums)..." }, perc: 0.003429 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Integrity check passed: 14822 files verified" }, perc: 0.001765 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Loading environment variables..." }, perc: 0.004233 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Environment loaded: 84 variables set" }, perc: 0.001464 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting shell profile initialization..." }, perc: 0.003268 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Shell profiles loaded for all users" }, perc: 0.00095 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Finalizing device tree..." }, perc: 0.005133 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Device tree finalized: 96 nodes" }, perc: 0.001214 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Releasing boot lock..." }, perc: 0.004136 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Boot lock released" }, perc: 0.000603 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting user session services..." }, perc: 0.003818 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "User session services started" }, perc: 0.000553 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Checking for pending kernel updates..." }, perc: 0.001193 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "No pending kernel updates" }, perc: 0.001173 },
    { opening_br: { output: "[" }, message_type: { output: "INFO" }, closing_br: { output: "]" }, text: { output: "Starting login manager..." }, perc: 0.002106 },
    { opening_br: { output: "[" }, message_type: { output: "SUCCESS", color_class: "success" }, closing_br: { output: "]" }, text: { output: "Login manager ready, awaiting user input" }, perc: 0.001344 },
]