export interface output_d{
    output: string
    color_class?: string
}
export interface output_line{
    message_type: output_d
    text: output_d
    perc: number
}
 
export const shuttingDownLines: output_line[] = [
    { message_type: { output: "INFO" }, text: { output: "Shutdown signal received..." }, perc: 0.008257 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Shutdown authorization verified" }, perc: 0.001376 },
    { message_type: { output: "INFO" }, text: { output: "Notifying active user sessions..." }, perc: 0.011871 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Session notification sent to 1 user" }, perc: 0.003917 },
    { message_type: { output: "INFO" }, text: { output: "Saving user session state..." }, perc: 0.007184 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Session state saved" }, perc: 0.003009 },
    { message_type: { output: "INFO" }, text: { output: "Closing open applications..." }, perc: 0.004807 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Application 'Text Editor' closed cleanly" }, perc: 0.00147 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Application 'Web Browser' closed cleanly" }, perc: 0.001703 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Application 'Media Player' not responding, waiting..." }, perc: 0.046468 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Application 'Media Player' closed" }, perc: 0.001437 },
    { message_type: { output: "INFO" }, text: { output: "Flushing clipboard manager..." }, perc: 0.011926 },
    { message_type: { output: "INFO" }, text: { output: "Stopping compositor..." }, perc: 0.00345 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Compositor stopped" }, perc: 0.001371 },
    { message_type: { output: "INFO" }, text: { output: "Stopping window manager..." }, perc: 0.003624 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Window manager stopped" }, perc: 0.00338 },
    { message_type: { output: "INFO" }, text: { output: "Stopping display manager..." }, perc: 0.006237 },
    { message_type: { output: "INFO" }, text: { output: "Terminating user session services..." }, perc: 0.007227 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "User session services terminated" }, perc: 0.001833 },
    { message_type: { output: "INFO" }, text: { output: "Stopping desktop search indexer..." }, perc: 0.008786 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Search indexer stopped" }, perc: 0.002105 },
    { message_type: { output: "INFO" }, text: { output: "Saving open document state..." }, perc: 0.004748 },
    { message_type: { output: "INFO" }, text: { output: "Unmounting home directory..." }, perc: 0.006836 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Home directory unmounted" }, perc: 0.001758 },
    { message_type: { output: "INFO" }, text: { output: "Stopping notification daemon..." }, perc: 0.003831 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Notification daemon stopped" }, perc: 0.003567 },
    { message_type: { output: "INFO" }, text: { output: "Stopping clipboard sync..." }, perc: 0.009188 },
    { message_type: { output: "INFO" }, text: { output: "Stopping crash reporter service..." }, perc: 0.009044 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Crash reporter stopped" }, perc: 0.003773 },
    { message_type: { output: "INFO" }, text: { output: "Stopping resource monitor..." }, perc: 0.006502 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Resource monitor stopped" }, perc: 0.002019 },
    { message_type: { output: "INFO" }, text: { output: "Stopping telemetry collector..." }, perc: 0.006768 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Telemetry buffer not fully flushed, discarding remainder" }, perc: 0.008753 },
    { message_type: { output: "INFO" }, text: { output: "Stopping backup scheduler..." }, perc: 0.009083 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Backup scheduler stopped" }, perc: 0.00072 },
    { message_type: { output: "INFO" }, text: { output: "Cancelling pending backup jobs..." }, perc: 0.007155 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "2 pending backup jobs cancelled" }, perc: 0.002562 },
    { message_type: { output: "INFO" }, text: { output: "Stopping VPN client service..." }, perc: 0.006039 },
    { message_type: { output: "INFO" }, text: { output: "Stopping firewall connection tracking..." }, perc: 0.002994 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Connection tracking table cleared" }, perc: 0.003153 },
    { message_type: { output: "INFO" }, text: { output: "Flushing DNS cache..." }, perc: 0.002877 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "DNS cache flushed" }, perc: 0.002664 },
    { message_type: { output: "INFO" }, text: { output: "Closing network connections..." }, perc: 0.004231 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "3 connections closed forcibly after timeout" }, perc: 0.052136 },
    { message_type: { output: "INFO" }, text: { output: "Releasing DHCP lease..." }, perc: 0.00449 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "DHCP lease released" }, perc: 0.000926 },
    { message_type: { output: "INFO" }, text: { output: "Bringing down network interfaces..." }, perc: 0.004207 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "eth0 interface down" }, perc: 0.003084 },
    { message_type: { output: "INFO" }, text: { output: "Stopping SSH daemon..." }, perc: 0.009641 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "sshd stopped" }, perc: 0.001961 },
    { message_type: { output: "INFO" }, text: { output: "Stopping firewall..." }, perc: 0.008927 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Firewall rules unloaded" }, perc: 0.002353 },
    { message_type: { output: "INFO" }, text: { output: "Stopping mail transfer agent..." }, perc: 0.007479 },
    { message_type: { output: "INFO" }, text: { output: "Stopping print spooler..." }, perc: 0.01103 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "CUPS daemon stopped" }, perc: 0.001782 },
    { message_type: { output: "INFO" }, text: { output: "Stopping Bluetooth stack..." }, perc: 0.010975 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Bluetooth adapter powered down" }, perc: 0.003106 },
    { message_type: { output: "INFO" }, text: { output: "Stopping audio subsystem..." }, perc: 0.009219 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "ALSA sound card released" }, perc: 0.000718 },
    { message_type: { output: "INFO" }, text: { output: "Stopping webcam service..." }, perc: 0.003579 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Webcam released" }, perc: 0.000809 },
    { message_type: { output: "INFO" }, text: { output: "Releasing GPU compute context..." }, perc: 0.006042 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "CUDA context released" }, perc: 0.003994 },
    { message_type: { output: "INFO" }, text: { output: "Stopping compositor vsync thread..." }, perc: 0.011029 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Vsync thread stopped" }, perc: 0.00362 },
    { message_type: { output: "INFO" }, text: { output: "Stopping container runtime..." }, perc: 0.003907 },
    { message_type: { output: "INFO" }, text: { output: "Stopping running containers..." }, perc: 0.009429 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "3 containers stopped gracefully" }, perc: 0.003396 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Container 'worker-2' did not stop in time, killing" }, perc: 0.012279 },
    { message_type: { output: "INFO" }, text: { output: "Stopping cron scheduler..." }, perc: 0.010243 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Cron scheduler stopped, 6 jobs deferred" }, perc: 0.001186 },
    { message_type: { output: "INFO" }, text: { output: "Stopping audit daemon..." }, perc: 0.004471 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "auditd stopped, logs flushed" }, perc: 0.003459 },
    { message_type: { output: "INFO" }, text: { output: "Stopping system logger..." }, perc: 0.009735 },
    { message_type: { output: "INFO" }, text: { output: "Stopping kernel log daemon..." }, perc: 0.011186 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "klogd stopped" }, perc: 0.002253 },
    { message_type: { output: "INFO" }, text: { output: "Flushing filesystem write cache..." }, perc: 0.011159 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Write cache flushed: 128MB written" }, perc: 0.001183 },
    { message_type: { output: "INFO" }, text: { output: "Syncing filesystem buffers..." }, perc: 0.011795 },
    { message_type: { output: "INFO" }, text: { output: "Committing pending journal entries..." }, perc: 0.011111 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Journal entries committed" }, perc: 0.001873 },
    { message_type: { output: "INFO" }, text: { output: "Stopping log rotation service..." }, perc: 0.003424 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "logrotate stopped" }, perc: 0.002609 },
    { message_type: { output: "INFO" }, text: { output: "Unmounting network shares..." }, perc: 0.009274 },
    { message_type: { output: "INFO" }, text: { output: "Unmounting /var partition..." }, perc: 0.006085 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "/var unmounted" }, perc: 0.000897 },
    { message_type: { output: "INFO" }, text: { output: "Unmounting /tmp..." }, perc: 0.00541 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "/tmp unmounted" }, perc: 0.003571 },
    { message_type: { output: "INFO" }, text: { output: "Purging temporary files..." }, perc: 0.003641 },
    { message_type: { output: "INFO" }, text: { output: "Stopping D-Bus system bus..." }, perc: 0.011608 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "D-Bus system bus stopped" }, perc: 0.001568 },
    { message_type: { output: "INFO" }, text: { output: "Deregistering services from D-Bus..." }, perc: 0.004712 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "32 services deregistered" }, perc: 0.001088 },
    { message_type: { output: "INFO" }, text: { output: "Stopping hardware abstraction layer..." }, perc: 0.01202 },
    { message_type: { output: "INFO" }, text: { output: "Stopping thermal management..." }, perc: 0.011267 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Thermal monitoring stopped" }, perc: 0.001809 },
    { message_type: { output: "INFO" }, text: { output: "Powering down fan controller..." }, perc: 0.003688 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Fan controller set to idle" }, perc: 0.002974 },
    { message_type: { output: "INFO" }, text: { output: "Stopping power management daemon..." }, perc: 0.01114 },
    { message_type: { output: "INFO" }, text: { output: "Saving battery calibration data..." }, perc: 0.002902 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Battery calibration data saved" }, perc: 0.002903 },
    { message_type: { output: "INFO" }, text: { output: "Stopping UPS monitoring daemon..." }, perc: 0.01085 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "UPS monitoring stopped" }, perc: 0.002296 },
    { message_type: { output: "INFO" }, text: { output: "Stopping RAID controller..." }, perc: 0.008146 },
    { message_type: { output: "INFO" }, text: { output: "Unmounting encrypted volume..." }, perc: 0.010356 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Encrypted volume unmounted" }, perc: 0.001528 },
    { message_type: { output: "INFO" }, text: { output: "Sealing disk encryption keys..." }, perc: 0.005359 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Encryption keys sealed" }, perc: 0.002999 },
    { message_type: { output: "INFO" }, text: { output: "Stopping TPM services..." }, perc: 0.007986 },
    { message_type: { output: "INFO" }, text: { output: "Deactivating LVM volume groups..." }, perc: 0.007826 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Logical volume 'lv-swap' deactivated" }, perc: 0.001862 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Logical volume 'lv-root' deactivated" }, perc: 0.003963 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Volume group 'vg0' deactivated" }, perc: 0.001701 },
    { message_type: { output: "INFO" }, text: { output: "Disabling swap partition..." }, perc: 0.009176 },
    { message_type: { output: "INFO" }, text: { output: "Stopping device mapper..." }, perc: 0.011202 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Device mapper stopped" }, perc: 0.002094 },
    { message_type: { output: "INFO" }, text: { output: "Releasing cgroups hierarchy..." }, perc: 0.003299 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "cgroup hierarchy released" }, perc: 0.001465 },
    { message_type: { output: "INFO" }, text: { output: "Stopping hardware watchdog..." }, perc: 0.003412 },
    { message_type: { output: "INFO" }, text: { output: "Unloading kernel modules..." }, perc: 0.004182 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Module nvidia.ko unloaded" }, perc: 0.001117 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Module snd_hda_intel.ko unloaded" }, perc: 0.001891 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "Module btrfs.ko busy, deferring unload" }, perc: 0.049171 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Module usbcore.ko unloaded" }, perc: 0.002256 },
    { message_type: { output: "INFO" }, text: { output: "Stopping udev device manager..." }, perc: 0.009047 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "udev daemon stopped" }, perc: 0.003055 },
    { message_type: { output: "INFO" }, text: { output: "Powering down USB devices..." }, perc: 0.009255 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "USB devices powered down" }, perc: 0.001967 },
    { message_type: { output: "INFO" }, text: { output: "Powering down PCIe devices..." }, perc: 0.009026 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "PCIe devices powered down" }, perc: 0.002613 },
    { message_type: { output: "INFO" }, text: { output: "Saving system entropy pool..." }, perc: 0.003988 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Entropy pool saved for next boot" }, perc: 0.002599 },
    { message_type: { output: "INFO" }, text: { output: "Writing shutdown reason to log..." }, perc: 0.005784 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Shutdown reason logged: user requested" }, perc: 0.003053 },
    { message_type: { output: "INFO" }, text: { output: "Recording shutdown timestamp..." }, perc: 0.009702 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: `Shutdown timestamp recorded: ${new Date().toISOString()}` }, perc: 0.001536 },
    { message_type: { output: "INFO" }, text: { output: "Stopping init system services..." }, perc: 0.006883 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "All init services stopped" }, perc: 0.002282 },
    { message_type: { output: "INFO" }, text: { output: "Sending SIGTERM to remaining processes..." }, perc: 0.005582 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "38 processes terminated gracefully" }, perc: 0.000838 },
    { message_type: { output: "WARNING", color_class: "warning" }, text: { output: "4 processes did not respond to SIGTERM" }, perc: 0.00566 },
    { message_type: { output: "INFO" }, text: { output: "Sending SIGKILL to remaining processes..." }, perc: 0.012131 },
    { message_type: { output: "INFO" }, text: { output: "Verifying no processes remain..." }, perc: 0.009751 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Process table clear" }, perc: 0.002226 },
    { message_type: { output: "INFO" }, text: { output: "Unmounting root filesystem..." }, perc: 0.009061 },
    { message_type: { output: "ERROR", color_class: "error" }, text: { output: "Failed to unmount /dev/sda1: filesystem busy" }, perc: 0.016753 },
    { message_type: { output: "INFO" }, text: { output: "Forcing remount as read-only..." }, perc: 0.009473 },
    { message_type: { output: "INFO" }, text: { output: "Flushing final disk writes..." }, perc: 0.011735 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Final disk writes flushed" }, perc: 0.003392 },
    { message_type: { output: "INFO" }, text: { output: "Disabling remaining interrupts..." }, perc: 0.007165 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Interrupts disabled" }, perc: 0.004125 },
    { message_type: { output: "INFO" }, text: { output: "Halting CPU cores..." }, perc: 0.011465 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "CPU core 2 halted" }, perc: 0.0009 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "CPU core 3 halted" }, perc: 0.002132 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "CPU core 4 halted" }, perc: 0.002273 },
    { message_type: { output: "INFO" }, text: { output: "Preparing power-off signal..." }, perc: 0.005368 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Power-off signal ready" }, perc: 0.002845 },
    { message_type: { output: "INFO" }, text: { output: "Notifying BIOS/UEFI firmware..." }, perc: 0.004138 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Firmware acknowledged shutdown request" }, perc: 0.003301 },
    { message_type: { output: "INFO" }, text: { output: "Finalizing shutdown sequence..." }, perc: 0.010859 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "All systems powered down cleanly" }, perc: 0.000912 },
    { message_type: { output: "INFO" }, text: { output: "System halt complete" }, perc: 0.009301 },
    { message_type: { output: "SUCCESS", color_class: "success" }, text: { output: "Safe to power off" }, perc: 0.001622 },
]